name: Django CI

on:
  schedule:
    - cron: 0 20 * * *
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        sudo apt-get install libmysqlclient-dev python3-dev python3-setuptools
        sudo pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        python3 -m pip list
        whereis python3
        /opt/hostedtoolcache/Python/3.7.9/x64/bin/python3 -m pip list
        /usr/lib/python3.7 -m pip list
        /usr/share/python3  -m pip list
